### PR TITLE
Changes to display queries from newest to oldest

### LINKED ISSUE #2: Records need to be displayed from newest to oldest
Records are currently rendered from oldest to newest on the queries index page. They should instead be rendered 
from newest to oldest.

### PR DESCRIPTION
**Pull request by Dinesh100K**
Added a default scope in query model
closes #2

### CODE REVIEW

**Comment by gonzonieto** [comment]
Well done! Good use of `default_scope`
Merging with `main`

**Review by gonzonieto — APPROVED** [review]
LGTM!

**Comment by Dinesh100K** [comment]
Thank you so much. Let me know If I can work on more issues.

**Comment by gonzonieto** [comment]
@Dinesh100K 
Absolutely! I will begin to look at this project with the intention to identify more issues open to contribution

**Pull request merged**
